apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: cicd
  labels:
    app: mysql
data:
  MYSQL_DATABASE: crud_app



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cicd
  labels:
    app: mysql  
data:
  init.sql: |
      CREATE DATABASE IF NOT EXISTS crud_app;

      USE crud_app;

      CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        role ENUM('admin', 'viewer') NOT NULL DEFAULT 'viewer',
        is_active TINYINT(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );

