apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
data:
  MYSQL_DATABASE: {{ .Values.config.data.MYSQL_DATABASE  | quote }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backendInit.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
data:
  init.sql: |
    {{ .Values.backendInit.initSql | indent 4 }}
    
