apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
          - containerPort: {{ .Values.backend.containerPort }}
          env:
          - name: DB_HOST
            value: {{ .Values.backend.env.DB_HOST }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.backend.env.DB_USER_SECRET.name }}
                key: {{ .Values.backend.env.DB_USER_SECRET.key }}
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.backend.env.DB_PASS_SECRET.name }}
                key: {{ .Values.backend.env.DB_PASS_SECRET.key }}
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{  .Values.backend.env.DB_NAME_CONFIGMAP.name }}
                key: {{ .Values.backend.env.DB_NAME_CONFIGMAP.key }}