apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.mysql.containerPort }}
    targetPort: {{ .Values.mysql.containerPort }}
  selector:
    app: mysql
          
 