apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cicd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 5000
          env:
          - name: DB_HOST
            value: {{ .Values.env.DB_HOST }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.env.dbUserSecret.name }}
                key: {{ .Values.env.dbUserSecret.key }}
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.env.dbPasswordSecret.name }}
                key: {{ .Values.env.dbPasswordSecret.key }}
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.env.dbNameConfigMap.name }}
                key: {{ .Values.env.dbNameConfigMap.key }}


